services:
  - type: web
    name: timestamp-microservice
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 16
    autoDeploy: true
